/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.admin;

import BUS.StatisticsBUS;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BAO TRAN
 */
public class Revenue extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeDoanhThuPanel
     */
    public Revenue() {
        initComponents();
        DefaultTableModel modelNgay = new DefaultTableModel(new String[]{"Ngày", "Tổng doanh thu"}, 0);
        tableDoanhThuNgay.setModel(modelNgay);

        DefaultTableModel modelKhoang = new DefaultTableModel(new String[]{"Ngày bắt đầu", "Ngày kết thúc", "Tổng doanh thu"}, 0);
        tableDoanhThuKhoangNgay.setModel(modelKhoang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        btnOkNgay = new javax.swing.JButton();
        btnResetNgay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTuNgay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDenNgay = new javax.swing.JTextField();
        btnOkKhoangNgay = new javax.swing.JButton();
        btnResetKhoangNgay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDoanhThuNgay = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDoanhThuKhoangNgay = new javax.swing.JTable();

        setBackground(new java.awt.Color(250, 240, 215));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("THỐNG KÊ DOANH THU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Theo ngày (yyyy-MM-dd)");

        txtNgay.setBackground(new java.awt.Color(250, 240, 215));
        txtNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnOkNgay.setBackground(new java.awt.Color(102, 255, 102));
        btnOkNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOkNgay.setText("OK");
        btnOkNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkNgayActionPerformed(evt);
            }
        });

        btnResetNgay.setBackground(new java.awt.Color(241, 185, 4));
        btnResetNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetNgay.setText("Reset");
        btnResetNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetNgayActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Từ ngày (yyyy-MM-dd)");

        txtTuNgay.setBackground(new java.awt.Color(250, 240, 215));
        txtTuNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTuNgay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Đến ngày (yyyy-MM-dd)");

        txtDenNgay.setBackground(new java.awt.Color(250, 240, 215));
        txtDenNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDenNgay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnOkKhoangNgay.setBackground(new java.awt.Color(102, 255, 102));
        btnOkKhoangNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOkKhoangNgay.setText("OK");
        btnOkKhoangNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkKhoangNgayActionPerformed(evt);
            }
        });

        btnResetKhoangNgay.setBackground(new java.awt.Color(241, 185, 4));
        btnResetKhoangNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetKhoangNgay.setText("Reset");
        btnResetKhoangNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetKhoangNgayActionPerformed(evt);
            }
        });

        tableDoanhThuNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableDoanhThuNgay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ngày", "Tổng doanh thu"
            }
        ));
        jScrollPane1.setViewportView(tableDoanhThuNgay);

        tableDoanhThuKhoangNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableDoanhThuKhoangNgay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ngày bắt đầu", "Ngày kết thúc", "Tổng doanh thu"
            }
        ));
        jScrollPane2.setViewportView(tableDoanhThuKhoangNgay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNgay)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOkKhoangNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetKhoangNgay))
                    .addComponent(txtDenNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(txtTuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOkNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetNgay)))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetNgay)
                            .addComponent(btnOkNgay)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOkKhoangNgay)
                    .addComponent(btnResetKhoangNgay))
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetNgayActionPerformed
        txtNgay.setText("");
        DefaultTableModel model = (DefaultTableModel) tableDoanhThuNgay.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnResetNgayActionPerformed

    private void btnOkNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkNgayActionPerformed
        String ngayInput = txtNgay.getText().trim();

        if (!isValidDate(ngayInput)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng ngày yyyy-MM-dd", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            StatisticsBUS thongKeBUS = new StatisticsBUS();
            List<Object[]> data = thongKeBUS.getRevenueBySpecificDate(ngayInput);

            DefaultTableModel model = (DefaultTableModel) tableDoanhThuNgay.getModel();
            for (Object[] row : data) {
                model.addRow(row);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnOkNgayActionPerformed

    private void btnOkKhoangNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkKhoangNgayActionPerformed
        String tuNgayInput = txtTuNgay.getText().trim();
        String denNgayInput = txtDenNgay.getText().trim();

        if (!isValidDate(tuNgayInput) || !isValidDate(denNgayInput)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng ngày yyyy-MM-dd cho cả Từ ngày và Đến ngày", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            StatisticsBUS thongKeBUS = new StatisticsBUS();
            List<Object[]> data = thongKeBUS.getRevenueByDateRange(tuNgayInput, denNgayInput);

            DefaultTableModel model = (DefaultTableModel) tableDoanhThuKhoangNgay.getModel();
            for (Object[] row : data) {
                model.addRow(row); 
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnOkKhoangNgayActionPerformed

    private void btnResetKhoangNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetKhoangNgayActionPerformed
        txtTuNgay.setText("");
        txtDenNgay.setText("");

        DefaultTableModel model = (DefaultTableModel) tableDoanhThuKhoangNgay.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnResetKhoangNgayActionPerformed
    
    private boolean isValidDate(String inputDate) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false); // Không cho nhập bậy
        try {
            sdf.parse(inputDate);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkKhoangNgay;
    private javax.swing.JButton btnOkNgay;
    private javax.swing.JButton btnResetKhoangNgay;
    private javax.swing.JButton btnResetNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDoanhThuKhoangNgay;
    private javax.swing.JTable tableDoanhThuNgay;
    private javax.swing.JTextField txtDenNgay;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtTuNgay;
    // End of variables declaration//GEN-END:variables
}
