/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.admin;

import BUS.StatisticsBUS;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BAO TRAN
 */
public class Top5Products extends javax.swing.JPanel {

    /**
     * Creates new form Top5SanPhamPanel
     */
    public Top5Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNgayTop5 = new javax.swing.JTextField();
        btnOkNgay = new javax.swing.JButton();
        btnResetNgay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnOkThang = new javax.swing.JButton();
        btnResetThang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTop5Ngay = new javax.swing.JTable();
        txtThangTop5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTop5Thang = new javax.swing.JTable();

        setBackground(new java.awt.Color(250, 240, 215));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("TOP 5 SẢN PHẨM BÁN CHẠY");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Theo ngày (yyyy-MM-dd)");

        txtNgayTop5.setBackground(new java.awt.Color(250, 240, 215));
        txtNgayTop5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayTop5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnOkNgay.setBackground(new java.awt.Color(102, 255, 102));
        btnOkNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOkNgay.setText("OK");
        btnOkNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkNgayActionPerformed(evt);
            }
        });

        btnResetNgay.setBackground(new java.awt.Color(241, 185, 4));
        btnResetNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetNgay.setText("Reset");
        btnResetNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetNgayActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Theo tháng (yyyy-MM)");

        btnOkThang.setBackground(new java.awt.Color(102, 255, 102));
        btnOkThang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOkThang.setText("OK");
        btnOkThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkThangActionPerformed(evt);
            }
        });

        btnResetThang.setBackground(new java.awt.Color(241, 185, 4));
        btnResetThang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetThang.setText("Reset");
        btnResetThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetThangActionPerformed(evt);
            }
        });

        tableTop5Ngay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTop5Ngay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng bán"
            }
        ));
        jScrollPane1.setViewportView(tableTop5Ngay);

        txtThangTop5.setBackground(new java.awt.Color(250, 240, 215));
        txtThangTop5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtThangTop5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableTop5Thang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTop5Thang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, ""},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng bán"
            }
        ));
        jScrollPane2.setViewportView(tableTop5Thang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel1)
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtThangTop5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnOkThang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnResetThang)))
                            .addComponent(txtNgayTop5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOkNgay)
                        .addGap(77, 77, 77)
                        .addComponent(btnResetNgay)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayTop5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOkNgay)
                            .addComponent(btnResetNgay)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThangTop5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetThang)
                            .addComponent(btnOkThang))
                        .addContainerGap(140, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkNgayActionPerformed
        String ngayInput = txtNgayTop5.getText().trim();

        if (!isValidDate(ngayInput)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng yyyy-MM-dd", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            StatisticsBUS thongKeBUS = new StatisticsBUS();
            List<Object[]> data = thongKeBUS.getTop5ProductsByDay(ngayInput);

            DefaultTableModel model = (DefaultTableModel) tableTop5Ngay.getModel();
            model.setRowCount(0);
            
            for (Object[] row : data) {
                model.addRow(row); // [0]: Tên sản phẩm, [1]: Số lượng bán
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnOkNgayActionPerformed

    private void btnResetNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetNgayActionPerformed
        txtNgayTop5.setText("");
        DefaultTableModel model = (DefaultTableModel) tableTop5Ngay.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnResetNgayActionPerformed

    private void btnOkThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkThangActionPerformed
        String thangInput = txtThangTop5.getText().trim();

        if (!isValidMonth(thangInput)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng yyyy-MM", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            StatisticsBUS thongKeBUS = new StatisticsBUS();
            List<Object[]> data = thongKeBUS.getTop5ProductsByMonth(thangInput);

            DefaultTableModel model = (DefaultTableModel) tableTop5Thang.getModel();
            model.setRowCount(0);
            for (Object[] row : data) {
                model.addRow(row);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnOkThangActionPerformed

    private void btnResetThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetThangActionPerformed
        txtThangTop5.setText("");

        DefaultTableModel model = (DefaultTableModel) tableTop5Thang.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnResetThangActionPerformed

    private boolean isValidMonth(String inputMonth) {
        Pattern pattern = Pattern.compile("\\d{4}-\\d{2}");
        return pattern.matcher(inputMonth).matches();
    }
    
    private boolean isValidDate(String inputDate) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try {
            sdf.parse(inputDate);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkNgay;
    private javax.swing.JButton btnOkThang;
    private javax.swing.JButton btnResetNgay;
    private javax.swing.JButton btnResetThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableTop5Ngay;
    private javax.swing.JTable tableTop5Thang;
    private javax.swing.JTextField txtNgayTop5;
    private javax.swing.JTextField txtThangTop5;
    // End of variables declaration//GEN-END:variables
}
